/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AcceptInstitutionInvitationRequest } from '../../models/accept-institution-invitation-request';
import { InstitutionInvitationAccepted } from '../../models/institution-invitation-accepted';

export interface AcademyInvitationsAcceptPost$Params {
      body: AcceptInstitutionInvitationRequest
}

export function academyInvitationsAcceptPost(http: HttpClient, rootUrl: string, params: AcademyInvitationsAcceptPost$Params, context?: HttpContext): Observable<StrictHttpResponse<InstitutionInvitationAccepted>> {
  const rb = new RequestBuilder(rootUrl, academyInvitationsAcceptPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InstitutionInvitationAccepted>;
    })
  );
}

academyInvitationsAcceptPost.PATH = '/academy/invitations/accept';
