/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ReportsInstitutionsInstitutionIdCredentialsPerStudentGet$Params {
  institutionId: string;
  asOf?: string;
}

export function reportsInstitutionsInstitutionIdCredentialsPerStudentGet(http: HttpClient, rootUrl: string, params: ReportsInstitutionsInstitutionIdCredentialsPerStudentGet$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, reportsInstitutionsInstitutionIdCredentialsPerStudentGet.PATH, 'get');
  if (params) {
    rb.path('institutionId', params.institutionId, {});
    rb.query('asOf', params.asOf, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

reportsInstitutionsInstitutionIdCredentialsPerStudentGet.PATH = '/reports/institutions/{institutionId}/credentials-per-student';
