/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ReportsInstitutionsInstitutionIdCredentialReadsGet$Params {
  institutionId: string;
  from: string;
  to: string;
}

export function reportsInstitutionsInstitutionIdCredentialReadsGet(http: HttpClient, rootUrl: string, params: ReportsInstitutionsInstitutionIdCredentialReadsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, reportsInstitutionsInstitutionIdCredentialReadsGet.PATH, 'get');
  if (params) {
    rb.path('institutionId', params.institutionId, {});
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

reportsInstitutionsInstitutionIdCredentialReadsGet.PATH = '/reports/institutions/{institutionId}/credential-reads';
