/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ReportsInstitutionsInstitutionIdCredentialsIssuedGet$Params {
  institutionId: string;
  from?: string;
  to?: string;
}

export function reportsInstitutionsInstitutionIdCredentialsIssuedGet(http: HttpClient, rootUrl: string, params: ReportsInstitutionsInstitutionIdCredentialsIssuedGet$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, reportsInstitutionsInstitutionIdCredentialsIssuedGet.PATH, 'get');
  if (params) {
    rb.path('institutionId', params.institutionId, {});
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

reportsInstitutionsInstitutionIdCredentialsIssuedGet.PATH = '/reports/institutions/{institutionId}/credentials-issued';
