/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { IssuerCredentialsCredentialIdGet$Params as IssuerCredentialsCredentialIdGet$Params } from './fn/credentials/issuer-credentials-credential-id-get';
export { issuerCredentialsCredentialIdGet as issuerCredentialsCredentialIdGet } from './fn/credentials/issuer-credentials-credential-id-get';
export type { HealthGet$Params as HealthGet$Params } from './fn/health/health-get';
export { healthGet as healthGet } from './fn/health/health-get';
export type { IssuerHoldersMeCredentialsGet$Params as IssuerHoldersMeCredentialsGet$Params } from './fn/holder-credentials/issuer-holders-me-credentials-get';
export { issuerHoldersMeCredentialsGet as issuerHoldersMeCredentialsGet } from './fn/holder-credentials/issuer-holders-me-credentials-get';
export type { IssuerHoldersMeCredentialsCredentialIdGet$Params as IssuerHoldersMeCredentialsCredentialIdGet$Params } from './fn/holder-credentials/issuer-holders-me-credentials-credential-id-get';
export { issuerHoldersMeCredentialsCredentialIdGet as issuerHoldersMeCredentialsCredentialIdGet } from './fn/holder-credentials/issuer-holders-me-credentials-credential-id-get';
export type { IssuerInstitutionsInstitutionIdWalletPost$Params as IssuerInstitutionsInstitutionIdWalletPost$Params } from './fn/institution-issuer-wallet/issuer-institutions-institution-id-wallet-post';
export { issuerInstitutionsInstitutionIdWalletPost as issuerInstitutionsInstitutionIdWalletPost } from './fn/institution-issuer-wallet/issuer-institutions-institution-id-wallet-post';
export type { IssuerStudentsStudentIdTitlePost$Params as IssuerStudentsStudentIdTitlePost$Params } from './fn/student-titles/issuer-students-student-id-title-post';
export { issuerStudentsStudentIdTitlePost as issuerStudentsStudentIdTitlePost } from './fn/student-titles/issuer-students-student-id-title-post';
