/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { HolderCredentialAnchors } from './models/holder-credential-anchors';
export type { HolderCredentialDetail } from './models/holder-credential-detail';
export type { HolderCredentialIssuer } from './models/holder-credential-issuer';
export type { HolderCredentialSummary } from './models/holder-credential-summary';
export type { InstitutionIssuerWalletLinked } from './models/institution-issuer-wallet-linked';
export type { JsonElement } from './models/json-element';
export type { LinkInstitutionIssuerWalletRequest } from './models/link-institution-issuer-wallet-request';
export type { LinkStudentTitleRequest } from './models/link-student-title-request';
export type { ProblemDetails } from './models/problem-details';
export type { StudentTitleLinked } from './models/student-title-linked';
