/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AcceptInstitutionInvitationRequest {
  additionalData?: ({
} | null);
  displayName?: (string | null);
  token?: (string | null);
  walletAddress?: (string | null);
}
