/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AnchorsResponse {
  chainId: (number | string);
  contentHash: string;
  ipfsCid: string;
  transactionHash: string;
}
