/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CareerSummary {
  additionalData?: ({
} | null);
  code?: (string | null);
  createdAt?: (string | null);
  id?: (string | null);
  institutionId?: (string | null);
  isActive?: (boolean | null);
  name?: (string | null);
}
