/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UntypedNode } from '../models/untyped-node';
export interface CreateStudentRequest {
  additionalData?: ({
} | null);
  enrollmentYear?: (null | UntypedNode);
  externalReference?: (string | null);
  walletAddress?: (string | null);
}
