/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateStudentRequest {
  enrollmentYear: (number | string | null);
  externalReference: (string | null);
  walletAddress: (string | null);
}
