/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCareerRequest {
  additionalData?: ({
} | null);
  code?: (string | null);
  name?: (string | null);
}
