/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateInstitutionInvitationRequest {
  additionalData?: ({
} | null);
  createdByUserId?: (string | null);
  email?: (string | null);
  role?: (string | null);
}
