/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateInstitutionRequest {
  additionalData?: ({
} | null);
  code?: (string | null);
  contactEmail?: (string | null);
  countryCode?: (string | null);
  displayName?: (string | null);
  legalName?: (string | null);
  websiteUrl?: (string | null);
}
