/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AnchorsResponse } from '../models/anchors-response';
import { IssuerResponse } from '../models/issuer-response';
export interface CredentialResponse {
  anchors: AnchorsResponse;
  expiresAt: (string | null);
  id: string;
  issuedAt: string;
  issuer: IssuerResponse;
  status: string;
  subjectDid: string;
  type: string;
}
