/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CredentialSummary {
  careerId: (string | null);
  contentHash: string;
  credentialId: string;
  credentialTypeCode: string;
  institutionId: string;
  ipfsCid: string;
  ipfsGatewayUrl: string;
  issuedAt: string;
  issuerDid: string;
  revocationReason: (string | null);
  revokedAt: (string | null);
  status: string;
  studentId: string;
  studentLabel: (string | null);
  subjectDid: string;
  transactionHash: string;
}
