/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CredentialRevoked {
  credentialId: string;
  institutionId: string;
  revocationReason: (string | null);
  revocationTxHash: string;
  revokedAt: string;
  status: string;
  studentId: string;
}
