/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MethodBase } from '../models/method-base';
export interface Exception {
  data?: ({
} | null);
  hResult?: (number | string);
  helpLink?: (string | null);
  innerException?: Exception;
  message?: (string | null);
  source?: (string | null);
  stackTrace?: (string | null);
  targetSite?: MethodBase;
}
