/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HolderCredentialAnchors } from '../models/holder-credential-anchors';
import { HolderCredentialIssuer } from '../models/holder-credential-issuer';
export interface HolderCredentialDetail {
  anchors: HolderCredentialAnchors;
  expiresAt: (string | null);
  id: string;
  issuedAt: string;
  issuer: HolderCredentialIssuer;
  issuerName: string;
  metadata: (string | null);
  revokedAt: (string | null);
  status: 'active' | 'revoked' | 'expired';
  subjectDid: string;
  title: string;
  typeCode: string;
}
