/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HolderCredentialAnchors {
  blockNumber: (number | string);
  chainId: (number | string);
  contentHash: string;
  eip712Signature: string;
  ipfsCid: string;
  ipfsGatewayUrl: string;
  transactionHash: string;
}
