/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HolderCredentialSummary {
  expiresAt: (string | null);
  id: string;
  issuedAt: string;
  issuerName: string;
  status: 'active' | 'revoked' | 'expired';
  title: string;
  typeCode: string;
}
