/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InstitutionInvitationAccepted {
  additionalData?: ({
} | null);
  did?: (string | null);
  institutionId?: (string | null);
  role?: (string | null);
  userId?: (string | null);
  walletAddress?: (string | null);
}
