/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InstitutionUserSummary {
  did: string;
  displayName: (string | null);
  email: (string | null);
  grantedAt: string;
  id: string;
  institutionId: string;
  revokedAt: (string | null);
  role: string;
  userId: string;
  walletAddress: string;
}
