/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { JsonElement } from '../models/json-element';
export interface LinkStudentTitleRequest {
  blockNumber: (number | string);
  careerId: (string | null);
  chainId: (number | string | null);
  contentHash: string;
  credentialTypeCode: string;
  eip712Signature: string;
  expiresAt: (string | null);
  ipfsCid: string;
  ipfsGatewayUrl: string;
  metadata: (null | JsonElement);
  transactionHash: string;
}
