/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LinkInstitutionIssuerWalletRequest {
  did: string;
  publicKey: (string | null);
  walletAddress: string;
}
