/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Exception } from '../models/exception';
import { MethodBase } from '../models/method-base';
import { UntypedNode } from '../models/untyped-node';
export interface ProblemDetails {
  additionalData?: ({
} | null);
  data?: ({
} | null);
  detail?: (string | null);
  hResult?: (number | string);
  helpLink?: (string | null);
  innerException?: Exception;
  instance?: (string | null);
  message?: (string | null);
  responseHeaders?: {
[key: string]: Array<string>;
};
  responseStatusCode?: (number | string);
  source?: (string | null);
  stackTrace?: (string | null);
  status?: (null | UntypedNode);
  targetSite?: MethodBase;
  title?: (string | null);
  type?: (string | null);
}
