/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RevokeCredentialRequest {
  blockNumber: (number | string);
  chainId: (number | string | null);
  eip712Signature: string;
  reason: string;
  revocationTxHash: string;
  revokedByUserId: (string | null);
}
