/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StudentWalletSummary {
  activatedAt: string;
  did: string;
  id: string;
  isPrimary: boolean;
  status: string;
  studentId: string;
  walletAddress: string;
}
