/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StudentTitleLinked {
  careerId: (string | null);
  credentialId: string;
  institutionId: string;
  issuedAt: string;
  issuedToWalletId: string;
  issuerDid: string;
  status: string;
  studentId: string;
  subjectDid: string;
}
