/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UntypedNode } from '../models/untyped-node';
export interface StudentSummary {
  additionalData?: ({
} | null);
  createdAt?: (string | null);
  enrollmentYear?: (null | UntypedNode);
  externalReference?: (string | null);
  id?: (string | null);
  institutionId?: (string | null);
  isActive?: (boolean | null);
  primaryWalletAddress?: (string | null);
  primaryWalletDid?: (string | null);
  primaryWalletId?: (string | null);
}
