/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateHolderProfileRequest {
  birthDate: (string | null);
  contactEmail: (string | null);
  countryCode: (string | null);
  displayName: (string | null);
  fullName: (string | null);
  phoneNumber: (string | null);
}
