/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VerificationChecksResponse {
  found: (boolean | null);
  hashMatches: (boolean | null);
  notExpired: (boolean | null);
  notRevoked: (boolean | null);
  onChainExists: (boolean | null);
  revocationSource: 'bd' | 'on_chain' | 'both';
  signatureValid: (boolean | null);
  validationSource: 'on_chain' | 'bd_fallback_inconclusive' | 'bd_fallback_rejected' | 'not_evaluated';
}
