/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HolderCredentialSummary } from '../../models/holder-credential-summary';

export interface IssuerHoldersMeCredentialsGet$Params {
}

export function issuerHoldersMeCredentialsGet(http: HttpClient, rootUrl: string, params?: IssuerHoldersMeCredentialsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<HolderCredentialSummary>>> {
  const rb = new RequestBuilder(rootUrl, issuerHoldersMeCredentialsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<HolderCredentialSummary>>;
    })
  );
}

issuerHoldersMeCredentialsGet.PATH = '/issuer/holders/me/credentials';
