/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AcademyInstitutionsPost$Params as AcademyInstitutionsPost$Params } from './fn/academy-institutions/academy-institutions-post';
export { academyInstitutionsPost as academyInstitutionsPost } from './fn/academy-institutions/academy-institutions-post';
export type { AcademyInstitutionsInstitutionIdGet$Params as AcademyInstitutionsInstitutionIdGet$Params } from './fn/academy-institutions/academy-institutions-institution-id-get';
export { academyInstitutionsInstitutionIdGet as academyInstitutionsInstitutionIdGet } from './fn/academy-institutions/academy-institutions-institution-id-get';
export type { AcademyInstitutionsInstitutionIdCareersPost$Params as AcademyInstitutionsInstitutionIdCareersPost$Params } from './fn/academy-institutions/academy-institutions-institution-id-careers-post';
export { academyInstitutionsInstitutionIdCareersPost as academyInstitutionsInstitutionIdCareersPost } from './fn/academy-institutions/academy-institutions-institution-id-careers-post';
export type { AcademyInstitutionsInstitutionIdStudentsPost$Params as AcademyInstitutionsInstitutionIdStudentsPost$Params } from './fn/academy-institutions/academy-institutions-institution-id-students-post';
export { academyInstitutionsInstitutionIdStudentsPost as academyInstitutionsInstitutionIdStudentsPost } from './fn/academy-institutions/academy-institutions-institution-id-students-post';
export type { AcademyInstitutionsInstitutionIdInvitationsPost$Params as AcademyInstitutionsInstitutionIdInvitationsPost$Params } from './fn/academy-institutions/academy-institutions-institution-id-invitations-post';
export { academyInstitutionsInstitutionIdInvitationsPost as academyInstitutionsInstitutionIdInvitationsPost } from './fn/academy-institutions/academy-institutions-institution-id-invitations-post';
export type { AcademyInvitationsAcceptPost$Params as AcademyInvitationsAcceptPost$Params } from './fn/academy-invitations/academy-invitations-accept-post';
export { academyInvitationsAcceptPost as academyInvitationsAcceptPost } from './fn/academy-invitations/academy-invitations-accept-post';
export type { IssuerCredentialsCredentialIdGet$Params as IssuerCredentialsCredentialIdGet$Params } from './fn/credentials/issuer-credentials-credential-id-get';
export { issuerCredentialsCredentialIdGet as issuerCredentialsCredentialIdGet } from './fn/credentials/issuer-credentials-credential-id-get';
export type { HealthGet$Params as HealthGet$Params } from './fn/health/health-get';
export { healthGet as healthGet } from './fn/health/health-get';
export type { IssuerHoldersMeCredentialsGet$Params as IssuerHoldersMeCredentialsGet$Params } from './fn/holder-credentials/issuer-holders-me-credentials-get';
export { issuerHoldersMeCredentialsGet as issuerHoldersMeCredentialsGet } from './fn/holder-credentials/issuer-holders-me-credentials-get';
export type { IssuerHoldersMeCredentialsCredentialIdGet$Params as IssuerHoldersMeCredentialsCredentialIdGet$Params } from './fn/holder-credentials/issuer-holders-me-credentials-credential-id-get';
export { issuerHoldersMeCredentialsCredentialIdGet as issuerHoldersMeCredentialsCredentialIdGet } from './fn/holder-credentials/issuer-holders-me-credentials-credential-id-get';
export type { IssuerInstitutionsInstitutionIdWalletPost$Params as IssuerInstitutionsInstitutionIdWalletPost$Params } from './fn/institution-issuer-wallet/issuer-institutions-institution-id-wallet-post';
export { issuerInstitutionsInstitutionIdWalletPost as issuerInstitutionsInstitutionIdWalletPost } from './fn/institution-issuer-wallet/issuer-institutions-institution-id-wallet-post';
export type { IssuerStudentsStudentIdTitlePost$Params as IssuerStudentsStudentIdTitlePost$Params } from './fn/student-titles/issuer-students-student-id-title-post';
export { issuerStudentsStudentIdTitlePost as issuerStudentsStudentIdTitlePost } from './fn/student-titles/issuer-students-student-id-title-post';
export type { VerificationsPost$Params as VerificationsPost$Params } from './fn/verifications/verifications-post';
export { verificationsPost as verificationsPost } from './fn/verifications/verifications-post';
