/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateHolderProfileRequest } from '../../models/update-holder-profile-request';

export interface AcademyHoldersMeProfilePut$Params {
      body: UpdateHolderProfileRequest
}

export function academyHoldersMeProfilePut(http: HttpClient, rootUrl: string, params: AcademyHoldersMeProfilePut$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, academyHoldersMeProfilePut.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

academyHoldersMeProfilePut.PATH = '/academy/holders/me/profile';
