/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AnchorsResponse } from './models/anchors-response';
export type { CredentialResponse } from './models/credential-response';
export type { IssuerResponse } from './models/issuer-response';
export type { ProblemDetails } from './models/problem-details';
export type { VerificationChecksResponse } from './models/verification-checks-response';
export type { VerificationRequest } from './models/verification-request';
export type { VerificationResponse } from './models/verification-response';
