/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CredentialRevoked } from '../../models/credential-revoked';
import { RevokeCredentialRequest } from '../../models/revoke-credential-request';

export interface IssuerCredentialsCredentialIdRevokePost$Params {
  credentialId: string;
      body: RevokeCredentialRequest
}

export function issuerCredentialsCredentialIdRevokePost(http: HttpClient, rootUrl: string, params: IssuerCredentialsCredentialIdRevokePost$Params, context?: HttpContext): Observable<StrictHttpResponse<CredentialRevoked>> {
  const rb = new RequestBuilder(rootUrl, issuerCredentialsCredentialIdRevokePost.PATH, 'post');
  if (params) {
    rb.path('credentialId', params.credentialId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CredentialRevoked>;
    })
  );
}

issuerCredentialsCredentialIdRevokePost.PATH = '/issuer/credentials/{credentialId}/revoke';
