/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HolderCredentialDetail } from '../../models/holder-credential-detail';

export interface IssuerCredentialsCredentialIdGet$Params {
  credentialId: string;
}

export function issuerCredentialsCredentialIdGet(http: HttpClient, rootUrl: string, params: IssuerCredentialsCredentialIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<HolderCredentialDetail>> {
  const rb = new RequestBuilder(rootUrl, issuerCredentialsCredentialIdGet.PATH, 'get');
  if (params) {
    rb.path('credentialId', params.credentialId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HolderCredentialDetail>;
    })
  );
}

issuerCredentialsCredentialIdGet.PATH = '/issuer/credentials/{credentialId}';
