/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InstitutionIssuerWalletLinked } from '../../models/institution-issuer-wallet-linked';
import { LinkInstitutionIssuerWalletRequest } from '../../models/link-institution-issuer-wallet-request';

export interface IssuerInstitutionsInstitutionIdWalletPost$Params {
  institutionId: string;
      body: LinkInstitutionIssuerWalletRequest
}

export function issuerInstitutionsInstitutionIdWalletPost(http: HttpClient, rootUrl: string, params: IssuerInstitutionsInstitutionIdWalletPost$Params, context?: HttpContext): Observable<StrictHttpResponse<InstitutionIssuerWalletLinked>> {
  const rb = new RequestBuilder(rootUrl, issuerInstitutionsInstitutionIdWalletPost.PATH, 'post');
  if (params) {
    rb.path('institutionId', params.institutionId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InstitutionIssuerWalletLinked>;
    })
  );
}

issuerInstitutionsInstitutionIdWalletPost.PATH = '/issuer/institutions/{institutionId}/wallet';
