CREATE TYPE "user_role" AS ENUM (
  'admin',
  'issuer',
  'student'
);

CREATE TYPE "credential_status" AS ENUM (
  'active',
  'revoked',
  'expired'
);

CREATE TYPE "verification_result" AS ENUM (
  'valid',
  'invalid_signature',
  'tampered',
  'revoked',
  'expired',
  'not_found',
  'ipfs_unreachable'
);

CREATE TYPE "wallet_status" AS ENUM (
  'active',
  'rotated',
  'revoked'
);

CREATE TABLE "credential_types" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(40) UNIQUE NOT NULL,
  "name" varchar(120) NOT NULL,
  "description" text,
  "allows_expiration" boolean NOT NULL DEFAULT false,
  "jsonld_context_url" varchar(500) NOT NULL,
  "schema_version" varchar(20) NOT NULL DEFAULT '1.0',
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "institutions" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "code" varchar(40) UNIQUE NOT NULL,
  "legal_name" varchar(200) NOT NULL,
  "display_name" varchar(120) NOT NULL,
  "did" varchar(200) UNIQUE NOT NULL,
  "issuer_wallet_address" varchar(42) UNIQUE NOT NULL,
  "public_key" text NOT NULL,
  "country_code" char(2) NOT NULL DEFAULT 'CL',
  "website_url" varchar(300),
  "is_active" boolean NOT NULL DEFAULT true,
  "registered_at" timestamp NOT NULL DEFAULT (now()),
  "deactivated_at" timestamp
);

CREATE TABLE "users" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "wallet_address" varchar(42) UNIQUE NOT NULL,
  "did" varchar(200) UNIQUE NOT NULL,
  "email" varchar(200) UNIQUE,
  "display_name" varchar(120),
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "last_login_at" timestamp
);

CREATE TABLE "institution_users" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "institution_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "role" user_role NOT NULL,
  "granted_by_user_id" uuid,
  "granted_at" timestamp NOT NULL DEFAULT (now()),
  "revoked_at" timestamp
);

CREATE TABLE "students" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "institution_id" uuid NOT NULL,
  "external_reference" varchar(80),
  "enrollment_year" int,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "student_wallets" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "student_id" uuid NOT NULL,
  "wallet_address" varchar(42) NOT NULL,
  "did" varchar(200) NOT NULL,
  "status" wallet_status NOT NULL DEFAULT 'active',
  "is_primary" boolean NOT NULL DEFAULT true,
  "activated_at" timestamp NOT NULL DEFAULT (now()),
  "rotated_at" timestamp,
  "rotation_reason" varchar(80)
);

CREATE TABLE "careers" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "institution_id" uuid NOT NULL,
  "code" varchar(40) NOT NULL,
  "name" varchar(200) NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "credentials" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "institution_id" uuid NOT NULL,
  "credential_type_id" int NOT NULL,
  "student_id" uuid NOT NULL,
  "career_id" uuid,
  "issued_to_wallet_id" uuid NOT NULL,
  "subject_did" varchar(200) NOT NULL,
  "issuer_did" varchar(200) NOT NULL,
  "ipfs_cid" varchar(80) UNIQUE NOT NULL,
  "ipfs_gateway_url" varchar(500) NOT NULL,
  "content_hash" char(66) UNIQUE NOT NULL,
  "transaction_hash" char(66) UNIQUE NOT NULL,
  "block_number" bigint NOT NULL,
  "chain_id" int NOT NULL DEFAULT 11155111,
  "eip712_signature" varchar(132) NOT NULL,
  "status" credential_status NOT NULL DEFAULT 'active',
  "issued_at" timestamp NOT NULL DEFAULT (now()),
  "expires_at" timestamp,
  "revoked_at" timestamp,
  "revoked_by_user_id" uuid,
  "revocation_reason" text,
  "revocation_tx_hash" char(66),
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "metadata" jsonb
);

CREATE TABLE "verification_logs" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "credential_id" uuid,
  "credential_id_query" varchar(80) NOT NULL,
  "result" verification_result NOT NULL,
  "error_detail" varchar(500),
  "verifier_ip" inet NOT NULL,
  "verifier_user_agent" varchar(500),
  "verifier_country" char(2),
  "verifier_referer" varchar(500),
  "verified_at" timestamp NOT NULL DEFAULT (now()),
  "duration_ms" int,
  "signature_valid" boolean,
  "hash_matches" boolean,
  "on_chain_exists" boolean,
  "not_revoked" boolean,
  "not_expired" boolean
);

CREATE TABLE "audit_logs" (
  "id" BIGSERIAL PRIMARY KEY,
  "institution_id" uuid,
  "actor_user_id" uuid,
  "actor_wallet_address" varchar(42),
  "action" varchar(80) NOT NULL,
  "entity_type" varchar(60) NOT NULL,
  "entity_id" varchar(80) NOT NULL,
  "success" boolean NOT NULL,
  "error_message" text,
  "ip_address" inet,
  "user_agent" varchar(500),
  "request_id" uuid,
  "payload" jsonb,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "institution_metrics_daily" (
  "id" BIGSERIAL PRIMARY KEY,
  "institution_id" uuid NOT NULL,
  "metric_date" date NOT NULL,
  "credentials_issued" int NOT NULL DEFAULT 0,
  "credentials_revoked" int NOT NULL DEFAULT 0,
  "verifications_total" int NOT NULL DEFAULT 0,
  "verifications_valid" int NOT NULL DEFAULT 0,
  "verifications_invalid" int NOT NULL DEFAULT 0,
  "unique_students_active" int NOT NULL DEFAULT 0,
  "computed_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "auth_challenges" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "nonce" varchar(40) UNIQUE NOT NULL,
  "wallet_address" varchar(42),
  "chain_id" int NOT NULL DEFAULT 11155111,
  "issued_at" timestamp NOT NULL DEFAULT (now()),
  "expires_at" timestamp NOT NULL,
  "consumed_at" timestamp
);

CREATE INDEX ON "institutions" ("code");

CREATE INDEX ON "institutions" ("did");

CREATE INDEX ON "institutions" ("issuer_wallet_address");

CREATE INDEX ON "institutions" ("is_active");

CREATE INDEX ON "users" ("wallet_address");

CREATE INDEX ON "users" ("did");

CREATE INDEX ON "users" ("is_active");

CREATE UNIQUE INDEX "uq_inst_user_role" ON "institution_users" ("institution_id", "user_id", "role");

CREATE INDEX ON "institution_users" ("institution_id");

CREATE INDEX ON "institution_users" ("user_id");

CREATE UNIQUE INDEX "uq_inst_external_ref" ON "students" ("institution_id", "external_reference");

CREATE INDEX ON "students" ("institution_id");

CREATE INDEX ON "student_wallets" ("student_id");

CREATE UNIQUE INDEX ON "student_wallets" ("wallet_address");

CREATE UNIQUE INDEX ON "student_wallets" ("did");

CREATE INDEX "idx_student_primary_wallet" ON "student_wallets" ("student_id", "is_primary");

CREATE UNIQUE INDEX "uq_inst_career_code" ON "careers" ("institution_id", "code");

CREATE INDEX ON "careers" ("institution_id");

CREATE INDEX ON "credentials" ("institution_id");

CREATE INDEX ON "credentials" ("student_id");

CREATE INDEX ON "credentials" ("issued_to_wallet_id");

CREATE INDEX ON "credentials" ("subject_did");

CREATE INDEX ON "credentials" ("issuer_did");

CREATE INDEX ON "credentials" ("ipfs_cid");

CREATE INDEX ON "credentials" ("content_hash");

CREATE INDEX ON "credentials" ("transaction_hash");

CREATE INDEX ON "credentials" ("status");

CREATE INDEX "idx_inst_status" ON "credentials" ("institution_id", "status");

CREATE INDEX "idx_student_status" ON "credentials" ("student_id", "status");

CREATE INDEX ON "credentials" ("issued_at");

CREATE INDEX ON "verification_logs" ("credential_id");

CREATE INDEX ON "verification_logs" ("credential_id_query");

CREATE INDEX ON "verification_logs" ("result");

CREATE INDEX ON "verification_logs" ("verified_at");

CREATE INDEX ON "verification_logs" ("verifier_ip");

CREATE INDEX "idx_cred_verified_at" ON "verification_logs" ("credential_id", "verified_at");

CREATE INDEX ON "audit_logs" ("institution_id");

CREATE INDEX ON "audit_logs" ("actor_user_id");

CREATE INDEX ON "audit_logs" ("action");

CREATE INDEX ON "audit_logs" ("entity_type");

CREATE INDEX "idx_entity" ON "audit_logs" ("entity_type", "entity_id");

CREATE INDEX ON "audit_logs" ("created_at");

CREATE UNIQUE INDEX "uq_inst_metric_date" ON "institution_metrics_daily" ("institution_id", "metric_date");

CREATE INDEX ON "institution_metrics_daily" ("metric_date");

CREATE INDEX ON "auth_challenges" ("nonce");

CREATE INDEX ON "auth_challenges" ("wallet_address");

CREATE INDEX ON "auth_challenges" ("expires_at");

COMMENT ON TABLE "credential_types" IS 'Catálogo de los 4 tipos del MVP: título, certificado de notas, certificación, diploma';

COMMENT ON COLUMN "credential_types"."code" IS 'Ej: TITULO, NOTAS, CERTIFICACION, DIPLOMA';

COMMENT ON COLUMN "credential_types"."allows_expiration" IS 'Si false, expires_at debe ser null';

COMMENT ON COLUMN "credential_types"."jsonld_context_url" IS 'URL del @context W3C para este tipo';

COMMENT ON TABLE "institutions" IS 'Cada institución es un tenant independiente. La clave privada NUNCA se almacena en BD.';

COMMENT ON COLUMN "institutions"."code" IS 'Identificador corto: DUOC, UCH, etc.';

COMMENT ON COLUMN "institutions"."did" IS 'DID del emisor institucional, ej: did:ethr:sepolia:0x...';

COMMENT ON COLUMN "institutions"."issuer_wallet_address" IS 'Dirección Ethereum del emisor (0x + 40 hex)';

COMMENT ON COLUMN "institutions"."public_key" IS 'Clave pública para verificación de firmas';

COMMENT ON COLUMN "institutions"."deactivated_at" IS 'Nullable. Si tiene valor, no puede emitir nuevas credenciales';

COMMENT ON TABLE "users" IS 'Usuario administrativo o emisor. Los alumnos viven en una tabla separada (anonimato máximo).';

COMMENT ON COLUMN "users"."wallet_address" IS 'Dirección Ethereum, autenticación vía SIWE';

COMMENT ON COLUMN "users"."did" IS 'did:ethr:sepolia:0x...';

COMMENT ON COLUMN "users"."email" IS 'Opcional. Solo para notificaciones administrativas, no para login';

COMMENT ON COLUMN "users"."display_name" IS 'Opcional. Solo para UI';

COMMENT ON TABLE "institution_users" IS 'Relación N:M entre usuarios e instituciones con rol específico';

COMMENT ON COLUMN "institution_users"."granted_by_user_id" IS 'Quién asignó este rol';

COMMENT ON COLUMN "institution_users"."revoked_at" IS 'Si tiene valor, el rol está inactivo';

COMMENT ON TABLE "students" IS 'Estudiante sin datos personales. La identidad real solo existe dentro de la VC en IPFS y en el SIS interno de la institución.';

COMMENT ON COLUMN "students"."external_reference" IS 'Ej: matrícula, RUT enmascarado, ID interno del SIS de la institución';

COMMENT ON COLUMN "students"."enrollment_year" IS 'Año de matrícula';

COMMENT ON TABLE "student_wallets" IS 'Historial de wallets de un estudiante. Las credenciales emitidas a wallets antiguas siguen siendo válidas.';

COMMENT ON COLUMN "student_wallets"."wallet_address" IS 'Dirección Ethereum del estudiante';

COMMENT ON COLUMN "student_wallets"."did" IS 'did:ethr:sepolia:0x... derivado de la wallet';

COMMENT ON COLUMN "student_wallets"."is_primary" IS 'Solo una wallet activa puede ser primaria por estudiante';

COMMENT ON COLUMN "student_wallets"."rotated_at" IS 'Cuándo se reemplazó por una nueva wallet';

COMMENT ON COLUMN "student_wallets"."rotation_reason" IS 'Motivo: compromised, voluntary, lost, etc.';

COMMENT ON TABLE "careers" IS 'Catálogo simple de carreras por institución. Sin versionado de planes de estudio (trabajo futuro).';

COMMENT ON COLUMN "careers"."code" IS 'Código interno: ING-SW, ENF, etc.';

COMMENT ON TABLE "credentials" IS 'Una credencial = un VC emitido. Datos personales NO se almacenan aquí, solo en el JSON-LD que vive en IPFS.';

COMMENT ON COLUMN "credentials"."id" IS 'UUID que también es el credentialId del VC';

COMMENT ON COLUMN "credentials"."career_id" IS 'Nullable: no todos los tipos requieren carrera (ej: diploma)';

COMMENT ON COLUMN "credentials"."issued_to_wallet_id" IS 'A qué wallet específica se emitió';

COMMENT ON COLUMN "credentials"."subject_did" IS 'DID del estudiante al momento de la emisión';

COMMENT ON COLUMN "credentials"."issuer_did" IS 'DID de la institución';

COMMENT ON COLUMN "credentials"."ipfs_cid" IS 'Content Identifier en IPFS, ej: bafybeig...';

COMMENT ON COLUMN "credentials"."ipfs_gateway_url" IS 'URL pública del gateway IPFS para acceso rápido';

COMMENT ON COLUMN "credentials"."content_hash" IS 'SHA-256 del JSON-LD, formato 0x + 64 hex';

COMMENT ON COLUMN "credentials"."transaction_hash" IS 'Hash de la tx en Sepolia, formato 0x + 64 hex';

COMMENT ON COLUMN "credentials"."block_number" IS 'Bloque donde se registró la credencial';

COMMENT ON COLUMN "credentials"."chain_id" IS 'Sepolia testnet';

COMMENT ON COLUMN "credentials"."eip712_signature" IS '0x + 130 hex = r || s || v';

COMMENT ON COLUMN "credentials"."expires_at" IS 'Nullable. Solo para tipos con allows_expiration = true';

COMMENT ON COLUMN "credentials"."revoked_at" IS 'Nullable. Si tiene valor, la credencial está revocada';

COMMENT ON COLUMN "credentials"."revoked_by_user_id" IS 'Usuario que ejecutó la revocación';

COMMENT ON COLUMN "credentials"."revocation_reason" IS 'Motivo de la revocación';

COMMENT ON COLUMN "credentials"."revocation_tx_hash" IS 'Hash de la tx de revocación en blockchain';

COMMENT ON COLUMN "credentials"."metadata" IS 'Datos adicionales no críticos: número de título, promedio, etc. (cache de lo que está en IPFS)';

COMMENT ON TABLE "verification_logs" IS 'Cada intento de verificación se registra completo. Sin datos del verificador identificables, solo metadatos técnicos.';

COMMENT ON COLUMN "verification_logs"."credential_id" IS 'Nullable: si no se encontró la credencial';

COMMENT ON COLUMN "verification_logs"."credential_id_query" IS 'ID consultado, incluso si no existe (para auditoría de intentos)';

COMMENT ON COLUMN "verification_logs"."error_detail" IS 'Detalle técnico del error, sin datos sensibles';

COMMENT ON COLUMN "verification_logs"."verifier_ip" IS 'IP del verificador anónimo';

COMMENT ON COLUMN "verification_logs"."verifier_country" IS 'Inferido por geoip';

COMMENT ON COLUMN "verification_logs"."verifier_referer" IS 'Origen de la verificación: QR scanner, app externa, etc.';

COMMENT ON COLUMN "verification_logs"."duration_ms" IS 'Tiempo total de la verificación end-to-end';

COMMENT ON COLUMN "verification_logs"."signature_valid" IS 'Pasó la verificación de firma EIP-712';

COMMENT ON COLUMN "verification_logs"."hash_matches" IS 'El hash on-chain coincide con el IPFS';

COMMENT ON COLUMN "verification_logs"."on_chain_exists" IS 'La credencial existe en la blockchain';

COMMENT ON COLUMN "verification_logs"."not_revoked" IS 'La credencial no está revocada';

COMMENT ON COLUMN "verification_logs"."not_expired" IS 'La credencial no está expirada';

COMMENT ON TABLE "audit_logs" IS 'Log inmutable de todas las operaciones administrativas. Append-only por convención.';

COMMENT ON COLUMN "audit_logs"."actor_user_id" IS 'Usuario que realizó la acción';

COMMENT ON COLUMN "audit_logs"."actor_wallet_address" IS 'Dirección que firmó la acción';

COMMENT ON COLUMN "audit_logs"."action" IS 'Ej: credential.issued, credential.revoked, role.granted';

COMMENT ON COLUMN "audit_logs"."entity_type" IS 'credential, user, role, institution, etc.';

COMMENT ON COLUMN "audit_logs"."request_id" IS 'Trace ID para correlación con logs estructurados';

COMMENT ON COLUMN "audit_logs"."payload" IS 'Snapshot de los datos relevantes, redactado de PII';

COMMENT ON TABLE "institution_metrics_daily" IS 'Snapshot diario de métricas por institución. Calculado por job nocturno.';

COMMENT ON TABLE "auth_challenges" IS 'Reto SIWE para autenticación. Actualmente en memoria, pero documentado en BD para futuro multi-instance.';

COMMENT ON COLUMN "auth_challenges"."wallet_address" IS 'Nullable hasta que se consuma';

COMMENT ON COLUMN "auth_challenges"."consumed_at" IS 'Nullable. Si tiene valor, el nonce fue usado';

ALTER TABLE "institution_users" ADD FOREIGN KEY ("institution_id") REFERENCES "institutions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "institution_users" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "institution_users" ADD FOREIGN KEY ("granted_by_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "students" ADD FOREIGN KEY ("institution_id") REFERENCES "institutions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "student_wallets" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "careers" ADD FOREIGN KEY ("institution_id") REFERENCES "institutions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "credentials" ADD FOREIGN KEY ("institution_id") REFERENCES "institutions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "credentials" ADD FOREIGN KEY ("credential_type_id") REFERENCES "credential_types" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "credentials" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "credentials" ADD FOREIGN KEY ("career_id") REFERENCES "careers" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "credentials" ADD FOREIGN KEY ("issued_to_wallet_id") REFERENCES "student_wallets" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "credentials" ADD FOREIGN KEY ("revoked_by_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "verification_logs" ADD FOREIGN KEY ("credential_id") REFERENCES "credentials" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("institution_id") REFERENCES "institutions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("actor_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "institution_metrics_daily" ADD FOREIGN KEY ("institution_id") REFERENCES "institutions" ("id") DEFERRABLE INITIALLY IMMEDIATE;
