/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Anclas verificables (IPFS / on-chain).
 */
export interface AnchorsResponse {
  chainId: (number | string);
  contentHash: string;
  ipfsCid: string;
  transactionHash: string;
}
