/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Emisor de la credencial (datos de `institutions`).
 */
export interface IssuerResponse {
  code: string;
  did: string;
  displayName: string;
}
