/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CredentialResponse } from '../models/credential-response';
import { VerificationChecksResponse } from '../models/verification-checks-response';

/**
 * Respuesta de `POST /verifications`: veredicto resumido, chequeos y credencial (o `null`).
 */
export interface VerificationResponse {
  checks: VerificationChecksResponse;
  credential: (null | CredentialResponse);
  result: 'valid' | 'revoked' | 'expired' | 'not_found';
}
