/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Booleanos por chequeo; `null` = no evaluado.
 */
export interface VerificationChecksResponse {
  found: (boolean | null);
  hashMatches: (boolean | null);
  notExpired: (boolean | null);
  notRevoked: (boolean | null);
  onChainExists: (boolean | null);
  signatureValid: (boolean | null);
}
