/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VerifyRequest } from '../../models/verify-request';
import { VerifyResponse } from '../../models/verify-response';

export interface AuthVerifyPost$Params {
      body: VerifyRequest
}

export function authVerifyPost(http: HttpClient, rootUrl: string, params: AuthVerifyPost$Params, context?: HttpContext): Observable<StrictHttpResponse<VerifyResponse>> {
  const rb = new RequestBuilder(rootUrl, authVerifyPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VerifyResponse>;
    })
  );
}

authVerifyPost.PATH = '/auth/verify';
