/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LinkStudentTitleRequest } from '../../models/link-student-title-request';
import { StudentTitleLinked } from '../../models/student-title-linked';

export interface IssuerStudentsStudentIdTitlePost$Params {
  studentId: string;
      body: LinkStudentTitleRequest
}

export function issuerStudentsStudentIdTitlePost(http: HttpClient, rootUrl: string, params: IssuerStudentsStudentIdTitlePost$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentTitleLinked>> {
  const rb = new RequestBuilder(rootUrl, issuerStudentsStudentIdTitlePost.PATH, 'post');
  if (params) {
    rb.path('studentId', params.studentId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StudentTitleLinked>;
    })
  );
}

issuerStudentsStudentIdTitlePost.PATH = '/issuer/students/{studentId}/title';
