// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Net;

namespace Auth.Infrastructure.Persistence.Entities;

/// <summary>
/// Log inmutable de todas las operaciones administrativas. Append-only por convención.
/// </summary>
public partial class AuditLog
{
    public long Id { get; set; }

    public Guid? InstitutionId { get; set; }

    /// <summary>
    /// Usuario que realizó la acción
    /// </summary>
    public Guid? ActorUserId { get; set; }

    /// <summary>
    /// Dirección que firmó la acción
    /// </summary>
    public string? ActorWalletAddress { get; set; }

    /// <summary>
    /// Ej: credential.issued, credential.revoked, role.granted
    /// </summary>
    public string Action { get; set; } = null!;

    /// <summary>
    /// credential, user, role, institution, etc.
    /// </summary>
    public string EntityType { get; set; } = null!;

    public string EntityId { get; set; } = null!;

    public bool Success { get; set; }

    public string? ErrorMessage { get; set; }

    public IPAddress? IpAddress { get; set; }

    public string? UserAgent { get; set; }

    /// <summary>
    /// Trace ID para correlación con logs estructurados
    /// </summary>
    public Guid? RequestId { get; set; }

    /// <summary>
    /// Snapshot de los datos relevantes, redactado de PII
    /// </summary>
    public string? Payload { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User? ActorUser { get; set; }

    public virtual Institution? Institution { get; set; }
}