// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Net;

namespace Auth.Infrastructure.Persistence.Entities;

/// <summary>
/// Cada intento de verificación se registra completo. Sin datos del verificador identificables, solo metadatos técnicos.
/// </summary>
public partial class VerificationLog
{
    public Guid Id { get; set; }

    /// <summary>
    /// Nullable: si no se encontró la credencial
    /// </summary>
    public Guid? CredentialId { get; set; }

    /// <summary>
    /// ID consultado, incluso si no existe (para auditoría de intentos)
    /// </summary>
    public string CredentialIdQuery { get; set; } = null!;

    /// <summary>
    /// Detalle técnico del error, sin datos sensibles
    /// </summary>
    public string? ErrorDetail { get; set; }

    /// <summary>
    /// IP del verificador anónimo
    /// </summary>
    public IPAddress VerifierIp { get; set; } = null!;

    public string? VerifierUserAgent { get; set; }

    /// <summary>
    /// Inferido por geoip
    /// </summary>
    public string? VerifierCountry { get; set; }

    /// <summary>
    /// Origen de la verificación: QR scanner, app externa, etc.
    /// </summary>
    public string? VerifierReferer { get; set; }

    public DateTime VerifiedAt { get; set; }

    /// <summary>
    /// Tiempo total de la verificación end-to-end
    /// </summary>
    public int? DurationMs { get; set; }

    /// <summary>
    /// Pasó la verificación de firma EIP-712
    /// </summary>
    public bool? SignatureValid { get; set; }

    /// <summary>
    /// El hash on-chain coincide con el IPFS
    /// </summary>
    public bool? HashMatches { get; set; }

    /// <summary>
    /// La credencial existe en la blockchain
    /// </summary>
    public bool? OnChainExists { get; set; }

    /// <summary>
    /// La credencial no está revocada
    /// </summary>
    public bool? NotRevoked { get; set; }

    /// <summary>
    /// La credencial no está expirada
    /// </summary>
    public bool? NotExpired { get; set; }

    public virtual Credential? Credential { get; set; }
}