/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InstitutionUserSummary } from '../../models/institution-user-summary';
import { UpdateInstitutionUserRoleRequest } from '../../models/update-institution-user-role-request';

export interface AcademyInstitutionsInstitutionIdUsersUserIdRolePatch$Params {
  institutionId: string;
  userId: string;
      body: UpdateInstitutionUserRoleRequest
}

export function academyInstitutionsInstitutionIdUsersUserIdRolePatch(http: HttpClient, rootUrl: string, params: AcademyInstitutionsInstitutionIdUsersUserIdRolePatch$Params, context?: HttpContext): Observable<StrictHttpResponse<InstitutionUserSummary>> {
  const rb = new RequestBuilder(rootUrl, academyInstitutionsInstitutionIdUsersUserIdRolePatch.PATH, 'patch');
  if (params) {
    rb.path('institutionId', params.institutionId, {});
    rb.path('userId', params.userId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InstitutionUserSummary>;
    })
  );
}

academyInstitutionsInstitutionIdUsersUserIdRolePatch.PATH = '/academy/institutions/{institutionId}/users/{userId}/role';
