/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateInstitutionInvitationRequest } from '../../models/create-institution-invitation-request';
import { InstitutionInvitationCreated } from '../../models/institution-invitation-created';

export interface AcademyInstitutionsInstitutionIdUsersInvitationsPost$Params {
  institutionId: string;
      body: CreateInstitutionInvitationRequest
}

export function academyInstitutionsInstitutionIdUsersInvitationsPost(http: HttpClient, rootUrl: string, params: AcademyInstitutionsInstitutionIdUsersInvitationsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<InstitutionInvitationCreated>> {
  const rb = new RequestBuilder(rootUrl, academyInstitutionsInstitutionIdUsersInvitationsPost.PATH, 'post');
  if (params) {
    rb.path('institutionId', params.institutionId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InstitutionInvitationCreated>;
    })
  );
}

academyInstitutionsInstitutionIdUsersInvitationsPost.PATH = '/academy/institutions/{institutionId}/users/invitations';
