/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AcademyInstitutionsInstitutionIdUsersUserIdDelete$Params {
  institutionId: string;
  userId: string;
}

export function academyInstitutionsInstitutionIdUsersUserIdDelete(http: HttpClient, rootUrl: string, params: AcademyInstitutionsInstitutionIdUsersUserIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, academyInstitutionsInstitutionIdUsersUserIdDelete.PATH, 'delete');
  if (params) {
    rb.path('institutionId', params.institutionId, {});
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

academyInstitutionsInstitutionIdUsersUserIdDelete.PATH = '/academy/institutions/{institutionId}/users/{userId}';
