/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateStudentRequest } from '../../models/create-student-request';
import { StudentSummary } from '../../models/student-summary';

export interface AcademyInstitutionsInstitutionIdStudentsPost$Params {
  institutionId: string;
      body: CreateStudentRequest
}

export function academyInstitutionsInstitutionIdStudentsPost(http: HttpClient, rootUrl: string, params: AcademyInstitutionsInstitutionIdStudentsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentSummary>> {
  const rb = new RequestBuilder(rootUrl, academyInstitutionsInstitutionIdStudentsPost.PATH, 'post');
  if (params) {
    rb.path('institutionId', params.institutionId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StudentSummary>;
    })
  );
}

academyInstitutionsInstitutionIdStudentsPost.PATH = '/academy/institutions/{institutionId}/students';
