/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InstitutionSummary } from '../../models/institution-summary';

export interface AcademyInstitutionsInstitutionIdGet$Params {
  institutionId: string;
}

export function academyInstitutionsInstitutionIdGet(http: HttpClient, rootUrl: string, params: AcademyInstitutionsInstitutionIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<InstitutionSummary>> {
  const rb = new RequestBuilder(rootUrl, academyInstitutionsInstitutionIdGet.PATH, 'get');
  if (params) {
    rb.path('institutionId', params.institutionId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InstitutionSummary>;
    })
  );
}

academyInstitutionsInstitutionIdGet.PATH = '/academy/institutions/{institutionId}';
