/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StudentSummary } from '../../models/student-summary';

export interface AcademyInstitutionsInstitutionIdStudentsStudentIdGet$Params {
  institutionId: string;
  studentId: string;
}

export function academyInstitutionsInstitutionIdStudentsStudentIdGet(http: HttpClient, rootUrl: string, params: AcademyInstitutionsInstitutionIdStudentsStudentIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentSummary>> {
  const rb = new RequestBuilder(rootUrl, academyInstitutionsInstitutionIdStudentsStudentIdGet.PATH, 'get');
  if (params) {
    rb.path('institutionId', params.institutionId, {});
    rb.path('studentId', params.studentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StudentSummary>;
    })
  );
}

academyInstitutionsInstitutionIdStudentsStudentIdGet.PATH = '/academy/institutions/{institutionId}/students/{studentId}';
