/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddStudentWalletRequest } from '../../models/add-student-wallet-request';
import { StudentWalletSummary } from '../../models/student-wallet-summary';

export interface AcademyInstitutionsInstitutionIdStudentsStudentIdWalletsPost$Params {
  institutionId: string;
  studentId: string;
      body: AddStudentWalletRequest
}

export function academyInstitutionsInstitutionIdStudentsStudentIdWalletsPost(http: HttpClient, rootUrl: string, params: AcademyInstitutionsInstitutionIdStudentsStudentIdWalletsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentWalletSummary>> {
  const rb = new RequestBuilder(rootUrl, academyInstitutionsInstitutionIdStudentsStudentIdWalletsPost.PATH, 'post');
  if (params) {
    rb.path('institutionId', params.institutionId, {});
    rb.path('studentId', params.studentId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StudentWalletSummary>;
    })
  );
}

academyInstitutionsInstitutionIdStudentsStudentIdWalletsPost.PATH = '/academy/institutions/{institutionId}/students/{studentId}/wallets';
