/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CareerSummary } from '../../models/career-summary';

export interface AcademyInstitutionsInstitutionIdCareersCareerIdGet$Params {
  institutionId: string;
  careerId: string;
}

export function academyInstitutionsInstitutionIdCareersCareerIdGet(http: HttpClient, rootUrl: string, params: AcademyInstitutionsInstitutionIdCareersCareerIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CareerSummary>> {
  const rb = new RequestBuilder(rootUrl, academyInstitutionsInstitutionIdCareersCareerIdGet.PATH, 'get');
  if (params) {
    rb.path('institutionId', params.institutionId, {});
    rb.path('careerId', params.careerId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CareerSummary>;
    })
  );
}

academyInstitutionsInstitutionIdCareersCareerIdGet.PATH = '/academy/institutions/{institutionId}/careers/{careerId}';
