/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InstitutionSummary } from '../../models/institution-summary';

export interface AcademyInstitutionsGet$Params {
}

export function academyInstitutionsGet(http: HttpClient, rootUrl: string, params?: AcademyInstitutionsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<InstitutionSummary>>> {
  const rb = new RequestBuilder(rootUrl, academyInstitutionsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<InstitutionSummary>>;
    })
  );
}

academyInstitutionsGet.PATH = '/academy/institutions';
