/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateInstitutionRequest } from '../../models/create-institution-request';
import { InstitutionCreated } from '../../models/institution-created';

export interface AcademyInstitutionsPost$Params {
      body: CreateInstitutionRequest
}

export function academyInstitutionsPost(http: HttpClient, rootUrl: string, params: AcademyInstitutionsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<InstitutionCreated>> {
  const rb = new RequestBuilder(rootUrl, academyInstitutionsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InstitutionCreated>;
    })
  );
}

academyInstitutionsPost.PATH = '/academy/institutions';
