/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CareerSummary } from '../../models/career-summary';
import { CreateCareerRequest } from '../../models/create-career-request';

export interface AcademyInstitutionsInstitutionIdCareersPost$Params {
  institutionId: string;
      body: CreateCareerRequest
}

export function academyInstitutionsInstitutionIdCareersPost(http: HttpClient, rootUrl: string, params: AcademyInstitutionsInstitutionIdCareersPost$Params, context?: HttpContext): Observable<StrictHttpResponse<CareerSummary>> {
  const rb = new RequestBuilder(rootUrl, academyInstitutionsInstitutionIdCareersPost.PATH, 'post');
  if (params) {
    rb.path('institutionId', params.institutionId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CareerSummary>;
    })
  );
}

academyInstitutionsInstitutionIdCareersPost.PATH = '/academy/institutions/{institutionId}/careers';
