/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StudentSummary } from '../../models/student-summary';

export interface AcademyInstitutionsInstitutionIdStudentsGet$Params {
  institutionId: string;
}

export function academyInstitutionsInstitutionIdStudentsGet(http: HttpClient, rootUrl: string, params: AcademyInstitutionsInstitutionIdStudentsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StudentSummary>>> {
  const rb = new RequestBuilder(rootUrl, academyInstitutionsInstitutionIdStudentsGet.PATH, 'get');
  if (params) {
    rb.path('institutionId', params.institutionId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<StudentSummary>>;
    })
  );
}

academyInstitutionsInstitutionIdStudentsGet.PATH = '/academy/institutions/{institutionId}/students';
