/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InstitutionUserSummary } from '../../models/institution-user-summary';

export interface AcademyInstitutionsInstitutionIdUsersGet$Params {
  institutionId: string;
}

export function academyInstitutionsInstitutionIdUsersGet(http: HttpClient, rootUrl: string, params: AcademyInstitutionsInstitutionIdUsersGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<InstitutionUserSummary>>> {
  const rb = new RequestBuilder(rootUrl, academyInstitutionsInstitutionIdUsersGet.PATH, 'get');
  if (params) {
    rb.path('institutionId', params.institutionId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<InstitutionUserSummary>>;
    })
  );
}

academyInstitutionsInstitutionIdUsersGet.PATH = '/academy/institutions/{institutionId}/users';
