/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VerificationRequest } from '../../models/verification-request';
import { VerificationResponse } from '../../models/verification-response';

export interface VerificationsPost$Params {
      body: VerificationRequest
}

export function verificationsPost(http: HttpClient, rootUrl: string, params: VerificationsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<VerificationResponse>> {
  const rb = new RequestBuilder(rootUrl, verificationsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VerificationResponse>;
    })
  );
}

verificationsPost.PATH = '/verifications';
