server {
    listen 80;
    server_name localhost;

    # 1. Servir la aplicación Angular (Frontend)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. API Gateway: Enrutar las peticiones al Backend (.NET)
    location /auth/ {
        proxy_pass http://auth-api:8080/auth/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'keep-alive';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /verifications {
        proxy_pass http://verifier-api:8080/verifications;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'keep-alive';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /issuer/ {
        proxy_pass http://issuer-api:8080/issuer/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'keep-alive';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}