/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MembershipResponse } from './membership-response';

export interface VerifyResponse {
  address: string;
  expiresAt: string;
  holder: boolean;
  jwt: string;
  memberships: Array<MembershipResponse>;
  platformAdmin: boolean;
  userId?: string | null;
}
