name: SovereignID CI Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-frontend:
    name: Build Angular WebApp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './src/web/package-lock.json'
          
      - name: Install Frontend Dependencies
        working-directory: ./src/web
        run: npm ci
        
      - name: Build Angular (Production)
        working-directory: ./src/web
        run: npm run build --configuration=production

  build-backend:
    name: Build .NET API Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          
      - name: Restore Backend Dependencies
        run: dotnet restore ./SovereignID.sln # Ajusta si tu archivo .sln tiene otro nombre o ruta
        
      - name: Build Backend (Release)
        run: dotnet build ./SovereignID.sln --no-restore --configuration Release